### ISSUE TITLE
Would like to contribute.

### ISSUE THREAD

**Issue by ppshobi** [realodix/plur#27]
Hey Guys, Really appreciate the work. I would like to dedicate some of my time to this project. would like to point to some issues I can take a look?

**Comment by realodix** [comment]
Hi @ppshobi, I really thank you if you want to dedicate some of your time to this project.

Maybe you can start from [/app/Helpers/UrlHlp.php#L42](https://github.com/realodix/plur/blob/master/app/Helpers/UrlHlp.php#L42), it doesn't support OpenGraph. But, if you have other ideas, feel free to send PR.

**Comment by ppshobi** [comment]
I didn't understand what you meant by don't support opengraph. But I have created a pull request by refactoring things a bit. Let me know what you think .

#28
